"""
Feed file loader.

Accepts two input formats from sophos-policy-checker:
  1. JSON  — the /analyze endpoint response body
  2. PDF   — the technical PDF report (parsed via pdfplumber)

Both return the same normalised list of finding dicts.

Usage:
    from feedfile import load_findings
    findings = load_findings("report.pdf")   # or .json
"""

import re
import json
from pathlib import Path

# ATT&CK technique ID pattern
_ATTCK_RE = re.compile(r"\b(T\d{4}(?:\.\d{3})?|TA\d{4})\b", re.IGNORECASE)

SEVERITIES = {"CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"}


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def load_findings(path: str) -> list[dict]:
    """
    Load and normalise findings from a JSON or PDF file.
    Auto-detects format from file extension.
    """
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"Feed file not found: {path}")

    suffix = p.suffix.lower()
    if suffix == ".pdf":
        return _load_pdf(p)
    elif suffix == ".json":
        return _load_json(p)
    else:
        raise ValueError(f"Unsupported file type '{suffix}'. Use .json or .pdf")


def load_findings_from_bytes(data: bytes, filename: str) -> list[dict]:
    """
    Load findings from raw bytes. Used by the web server upload handler.
    filename is used only to detect the file type.
    """
    suffix = Path(filename).suffix.lower()
    if suffix == ".pdf":
        return _parse_pdf_bytes(data)
    elif suffix == ".json":
        return _parse_json_bytes(data)
    else:
        raise ValueError(f"Unsupported file type '{suffix}'. Upload a .json or .pdf file.")


# ---------------------------------------------------------------------------
# JSON loader
# ---------------------------------------------------------------------------

def _parse_json_bytes(data: bytes) -> list[dict]:
    try:
        payload = json.loads(data.decode("utf-8"))
    except Exception as e:
        raise ValueError(f"Invalid JSON: {e}")

    if isinstance(payload, list):
        raw = payload
    elif isinstance(payload, dict):
        raw = payload.get("findings") or []
        if not raw:
            for key in ("results", "checks", "audit"):
                if key in payload:
                    raw = payload[key]
                    break
    else:
        raise ValueError("Unexpected JSON structure.")

    if not raw:
        raise ValueError("No findings found in JSON file.")

    return [_normalise(item) for item in raw if isinstance(item, dict)]


def _load_json(path: Path) -> list[dict]:
    return _parse_json_bytes(path.read_bytes())


# ---------------------------------------------------------------------------
# PDF loader
# ---------------------------------------------------------------------------

def _parse_pdf_bytes(data: bytes) -> list[dict]:
    """
    Extract findings from a sophos-policy-checker technical PDF report.

    The PDF is generated by WeasyPrint from HTML that structures each finding as:
      [SEVERITY]  Finding Title
      Finding     <detail text>
      Recommendation  <recommendation text>
      References  <list of refs incl. ATT&CK IDs>
      Affected Rules  <rule names>

    We extract full page text and split it into finding blocks using the
    severity keyword as a boundary marker.
    """
    try:
        import pdfplumber
        import io
    except ImportError:
        raise RuntimeError("pdfplumber is required for PDF parsing: pip install pdfplumber")

    with pdfplumber.open(io.BytesIO(data)) as pdf:
        pages_text = []
        for page in pdf.pages:
            text = page.extract_text(x_tolerance=2, y_tolerance=2)
            if text:
                pages_text.append(text)

    full_text = "\n".join(pages_text)

    if not full_text.strip():
        raise ValueError("Could not extract text from PDF. Make sure it is the sophos-policy-checker technical report (not the executive summary or a scanned image).")

    findings = _parse_pdf_text(full_text)

    if not findings:
        raise ValueError(
            "No findings detected in the PDF. "
            "Ensure you are uploading the technical PDF report from sophos-policy-checker, not the executive summary."
        )

    return findings


def _load_pdf(path: Path) -> list[dict]:
    return _parse_pdf_bytes(path.read_bytes())


def _parse_pdf_text(text: str) -> list[dict]:
    """
    Split the extracted PDF text into per-finding blocks and parse each one.

    Sophos-checker PDF pattern per finding block:
      Line starting with a severity word (CRITICAL/HIGH/MEDIUM/LOW/INFO)
      followed by the finding title on the same or next line.
      Then labelled rows: Finding, Recommendation, References, Affected Rules, Where to fix.
    """
    lines = [l.rstrip() for l in text.splitlines()]
    findings = []

    # Find line indices where a new finding starts (line begins with a severity word)
    sev_line_re = re.compile(
        r"^(CRITICAL|HIGH|MEDIUM|LOW|INFO)\b(.*)$", re.IGNORECASE
    )

    block_starts = []
    for i, line in enumerate(lines):
        m = sev_line_re.match(line.strip())
        if m:
            block_starts.append((i, m.group(1).upper(), m.group(2).strip()))

    # Slice text into per-finding blocks
    for idx, (start, severity, title_rest) in enumerate(block_starts):
        end = block_starts[idx + 1][0] if idx + 1 < len(block_starts) else len(lines)
        block_lines = lines[start:end]
        finding = _parse_finding_block(block_lines, severity, title_rest)
        if finding:
            findings.append(finding)

    return findings


def _parse_finding_block(lines: list[str], severity: str, title_rest: str) -> dict | None:
    """
    Parse a single finding block (lines between two severity markers).
    """
    # Title: the severity line remainder, or the next non-empty line
    title = title_rest.strip()
    if not title:
        for line in lines[1:4]:
            stripped = line.strip()
            if stripped and not stripped.upper() in SEVERITIES:
                title = stripped
                break

    if not title:
        return None

    # Walk remaining lines collecting labelled sections
    section_re = re.compile(
        r"^(Finding|Recommendation|References?|Affected Rules?|Where to fix|Category)\s*[:\-]?\s*(.*)$",
        re.IGNORECASE,
    )

    sections: dict[str, list[str]] = {}
    current_section = None

    for line in lines[1:]:
        stripped = line.strip()
        if not stripped:
            continue
        m = section_re.match(stripped)
        if m:
            current_section = m.group(1).lower().rstrip("s")  # normalise plural
            val = m.group(2).strip()
            sections[current_section] = [val] if val else []
        elif current_section:
            sections[current_section].append(stripped)

    def get_section(*keys: str) -> str:
        for k in keys:
            if k in sections:
                return " ".join(sections[k]).strip()
        return ""

    detail         = get_section("finding")
    recommendation = get_section("recommendation")
    category       = get_section("category") or _infer_category(title)

    # References: extract ATT&CK IDs and keep plain text refs too
    ref_text = get_section("reference")
    references = _extract_references(ref_text)

    # Affected rules: comma or newline separated rule names
    affected_text = get_section("affected rule", "where to fix")
    affected_rules = [r.strip() for r in re.split(r"[,\n]", affected_text) if r.strip()] if affected_text else []

    return _normalise({
        "severity":       severity,
        "category":       category,
        "title":          title,
        "detail":         detail,
        "recommendation": recommendation,
        "references":     references,
        "affected_rules": affected_rules,
        "affected_systems": [],
    })


def _extract_references(text: str) -> list[str]:
    """Pull ATT&CK IDs out of a reference string; keep them plus any OWASP/NIST tokens."""
    if not text:
        return []
    refs = []
    # ATT&CK IDs
    refs += [m.upper() for m in _ATTCK_RE.findall(text)]
    # OWASP
    refs += re.findall(r"OWASP\s+\S+", text, re.IGNORECASE)
    # NIST
    refs += re.findall(r"NIST\s+\S+(?:\s+\S+)?", text, re.IGNORECASE)
    return list(dict.fromkeys(refs))


def _infer_category(title: str) -> str:
    """Guess category from title keywords when the PDF doesn't include it."""
    lower = title.lower()
    if any(k in lower for k in ("vpn", "ipsec", "ssl vpn", "pptp", "l2tp")):
        return "VPN"
    if any(k in lower for k in ("firewall", "rule", "wan", "nat", "any-to-any")):
        return "Firewall Rules"
    if any(k in lower for k in ("log", "siem", "audit")):
        return "Logging"
    if any(k in lower for k in ("admin", "ssh", "https access", "management")):
        return "Administration"
    if any(k in lower for k in ("certificate", "tls", "ssl", "cipher")):
        return "Certificates"
    if any(k in lower for k in ("auth", "password", "mfa", "otp")):
        return "Authentication"
    return "General"


# ---------------------------------------------------------------------------
# Shared normaliser
# ---------------------------------------------------------------------------

def _normalise(item: dict) -> dict:
    return {
        "severity":         item.get("severity", "INFO").upper(),
        "category":         item.get("category", "General"),
        "title":            item.get("title", "Unnamed Finding"),
        "detail":           item.get("detail", ""),
        "recommendation":   item.get("recommendation", ""),
        "references":       item.get("references", []),
        "affected_rules":   item.get("affected_rules", []),
        "affected_systems": item.get("affected_systems", []),
    }


# ---------------------------------------------------------------------------
# ATT&CK ID extractor (used by engine.py)
# ---------------------------------------------------------------------------

def extract_technique_ids(finding: dict) -> list[str]:
    """Extract ATT&CK technique IDs from a finding's references list."""
    ids = []
    for ref in finding.get("references", []):
        ids.extend(m.upper() for m in _ATTCK_RE.findall(str(ref)))
    return list(dict.fromkeys(ids))
